# Data Manipuation

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../data.csv')
print(data.head(5))

   Employee_ID        Name   Age Department   Salary  Performance_Score
0            1  Employee_1  28.0      Sales  66048.0                4.0
1            2  Employee_2  35.0         HR  43434.0                9.0
2            3  Employee_3   NaN  Marketing  85302.0                1.0
3            4  Employee_4  22.0      Sales  58657.0                4.0
4            5  Employee_5  53.0  Marketing  33478.0                9.0

In [3]:
data.describe()

       Employee_ID        Age         Salary  Performance_Score
count     50.00000  48.000000      48.000000          48.000000
mean      25.50000  37.770833   73059.208333           5.250000
std       14.57738  11.567084   22921.864915           2.685659
min        1.00000  21.000000   33478.000000           1.000000
25%       13.25000  28.000000   55854.000000           3.000000
50%       25.50000  35.000000   68178.500000           5.000000
75%       37.75000  49.000000   87533.000000           8.000000
max       50.00000  59.000000  117841.000000          10.000000

In [5]:
data.dtypes

Employee_ID            int64
Name                     str
Age                  float64
Department               str
Salary               float64
Performance_Score    float64
dtype: object

## Handling missing values

In [ ]:
data.isnull() #true for nul or NaN values

    Employee_ID   Name    Age  Department  Salary  Performance_Score
0         False  False  False       False   False              False
1         False  False  False       False   False              False
2         False  False   True       False   False              False
3         False  False  False       False   False              False
4         False  False  False       False   False              False
5         False  False  False        True   False              False
6         False  False  False       False   False              False
7         False  False  False       False   False              False
8         False  False  False       False    True              False
9         False  False  False       False   False              False
10        False  False  False       False   False              False
11        False  False  False       False   False              False
12        False  False  False       False   False               True
13        False  False  False       False   False              False
14        False  False  False       False   False              False
15        False  False  False       False   False              False
16        False  False  False       False   False              False
17        False   True  False       False   False              False
18        False  False  False       False   False              False
19        False  False  False       False   False              False
20        False  False  False       False   False              False
21        False  False  False       False   False              False
22        False  False  False       False   False              False
23        False  False   True       False   False              False
24        False  False  False       False   False              False
25        False  False  False       False   False              False
26        False  False  False       False   False              False
27        False  False  False       False   False              False
28        False  False  False       False   False              False
29        False  False  False       False    True              False
30        False  False  False       False   False              False
31        False  False  False       False   False              False
32        False  False  False       False   False              False
33        False  False  False       False   False              False
34        False  False  False        True   False              False
35        False  False  False       False   False              False
36        False  False  False       False   False              False
37        False  False  False       False   False              False
38        False  False  False       False   False              False
39        False  False  False       False   False              False
40        False  False  False       False   False              False
41        False  False  False       False   False               True
42        False  False  False       False   False              False
43        False  False  False       False   False              False
44        False  False  False       False   False              False
45        False  False  False       False   False              False
46        False  False  False       False   False              False
47        False   True  False       False   False              False
48        False  False  False       False   False              False
49        False  False  False       False   False              False

In [ ]:
data.isnull().any(axis=1) #any value from columns

0     False
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34     True
35    False
36    False
37    False
38    False
39    False
40    False
41     True
42    False
43    False
44    False
45    False
46    False
47     True
48    False
49    False
dtype: bool

In [ ]:
data.isnull().Salary #isnull for column Salary

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: Salary, dtype: bool

In [ ]:
data.isnull().sum() #total null values wrt each columns

Employee_ID          0
Name                 2
Age                  2
Department           2
Salary               2
Performance_Score    2
dtype: int64

In [ ]:
#data.fillna(0) ---> #fills null with 'zero'

### Fill missing with mean

In [ ]:
data['Salary_fillNa'] = data['Salary'].fillna(data['Salary'].mean()) #we created new Salary_fillNa to fill null values of Salary in data with the mean of salary.
print(data['Salary_fillNa'])

0      66048.000000
1      43434.000000
2      85302.000000
3      58657.000000
4      33478.000000
5      84987.000000
6      66463.000000
7      74597.000000
8      73059.208333
9      42676.000000
10     64671.000000
11     46361.000000
12     68427.000000
13     55203.000000
14     67930.000000
15     79823.000000
16     51319.000000
17    117841.000000
18    113227.000000
19     51417.000000
20    113886.000000
21     37331.000000
22     82581.000000
23    104341.000000
24     81856.000000
25     48301.000000
26     64438.000000
27     82350.000000
28     96784.000000
29     73059.208333
30    108172.000000
31    108104.000000
32    102512.000000
33     64973.000000
34     86985.000000
35     64522.000000
36     43947.000000
37     56071.000000
38    100697.000000
39     72487.000000
40     77576.000000
41     61571.000000
42     93699.000000
43     46828.000000
44     64741.000000
45     57760.000000
46     82296.000000
47     89177.000000
48     38392.000000
49    102603.000000
Name: Salary_fillNa, dtype: float64

## Renaming Column

In [22]:
data = data.rename(columns={'Employee_ID':'EID'})
print(data.head(5))

   EID        Name   Age Department   Salary  Performance_Score  Salary_fillNa
0    1  Employee_1  28.0      Sales  66048.0                4.0        66048.0
1    2  Employee_2  35.0         HR  43434.0                9.0        43434.0
2    3  Employee_3   NaN  Marketing  85302.0                1.0        85302.0
3    4  Employee_4  22.0      Sales  58657.0                4.0        58657.0
4    5  Employee_5  53.0  Marketing  33478.0                9.0        33478.0

## Change data type

In [24]:
data.dtypes

EID                    int64
Name                     str
Age                  float64
Department               str
Salary               float64
Performance_Score    float64
Salary_fillNa        float64
dtype: object

In [29]:
data['Salary_new'] = data['Salary'].astype('Int64') #Int64 for null values (capital I)
print(data['Salary_new'].dtype)

Int64

##  Data Aggregating & Grouping

In [30]:
data.head(5)

,EID,Name,Age,Department,Salary,Performance_Score,Salary_fillNa,Salary_new
0,1,Employee_1,28.0,Sales,66048.0,4.0,66048.0,66048
1,2,Employee_2,35.0,HR,43434.0,9.0,43434.0,43434
2,3,Employee_3,NaN,Marketing,85302.0,1.0,85302.0,85302
3,4,Employee_4,22.0,Sales,58657.0,4.0,58657.0,58657
4,5,Employee_5,53.0,Marketing,33478.0,9.0,33478.0,33478

In [ ]:
grouped_mean = data.groupby('Age')['Performance_Score'].mean().astype(int) #mean perf score grouped by age
print(grouped_mean)

Age
21.0    8
22.0    4
23.0    3
25.0    3
26.0    3
28.0    4
30.0    3
31.0    3
32.0    5
33.0    5
34.0    8
35.0    6
36.0    6
43.0    3
44.0    5
45.0    8
48.0    6
49.0    1
50.0    7
53.0    6
54.0    1
55.0    8
56.0    9
59.0    9
Name: Performance_Score, dtype: int64

In [38]:
grouped_sum = data.groupby('Age')['Performance_Score'].sum()
print(grouped_sum)

Age
21.0     8.0
22.0    13.0
23.0     7.0
25.0     3.0
26.0    11.0
28.0    13.0
30.0     6.0
31.0     7.0
32.0     5.0
33.0    10.0
34.0     8.0
35.0    26.0
36.0     6.0
43.0     6.0
44.0    11.0
45.0    17.0
48.0     6.0
49.0     3.0
50.0    22.0
53.0    12.0
54.0     1.0
55.0    16.0
56.0    19.0
59.0     9.0
Name: Performance_Score, dtype: float64

In [44]:
##aggregate function
grouped_agg = data.groupby("Age")["Performance_Score"].agg(['mean', 'sum', 'count'])
print(grouped_agg)

          mean   sum  count
Age
21.0  8.000000   8.0      1
22.0  4.333333  13.0      3
23.0  3.500000   7.0      2
25.0  3.000000   3.0      1
26.0  3.666667  11.0      3
28.0  4.333333  13.0      3
30.0  3.000000   6.0      2
31.0  3.500000   7.0      2
32.0  5.000000   5.0      1
33.0  5.000000  10.0      2
34.0  8.000000   8.0      1
35.0  6.500000  26.0      4
36.0  6.000000   6.0      1
43.0  3.000000   6.0      2
44.0  5.500000  11.0      2
45.0  8.500000  17.0      2
48.0  6.000000   6.0      1
49.0  1.500000   3.0      2
50.0  7.333333  22.0      3
53.0  6.000000  12.0      2
54.0  1.000000   1.0      1
55.0  8.000000  16.0      2
56.0  9.500000  19.0      2
59.0  9.000000   9.0      1

## Merging and Joining

In [46]:
df1 = pd.DataFrame({'key':['A', 'B', 'C'], 'Val1':['1','2','3']})
df2 = pd.DataFrame({'key':['D', 'E', 'F'], 'Val1':['4','5','6']})